### PR TITLE
FIX: Crash when switching from favorites.

### PR DESCRIPTION
**Pull request by captainyarr**
- Added try/catch block to onDestroy function to catch typedef error causing an error when switching away from the favorites page.

### CODE REVIEW

**Comment by captainyarr** [comment]
The additional changes to the file are from whitespace changes and reformatting the code

**Comment by YIFYtorrents** [comment]
You have added more lines then you've have removed. +261 −257

Please don't remove whitespaces. Please don't reformat the code. I can't accept this pull request as I don't know what have been changed. A new version v.0.4.1 is coming very soon, I am very busy and I don't have time to review so much changes. Would you mind posting a new pull request, that just fixes the issue?

PS: The reformat makes me somewhow blind to see changes. Don't do the dirty job like reformats, whitespaces, etc. Anyways, thank you for the work.

**Comment by YIFYtorrents** [comment]
updated readme for this issue: https://github.com/PopcornTimeCommunity/desktop/commit/668905a215a80c3cde94cc1680f48c7847cfb7f7

**Comment by captainyarr** [comment]
Alright I'll redo the pull request. Its a small enough change.

**Pull request closed without merging**
