### PR TITLE
Sort torrents collection by last modified. Makes it easy to access last used torrents.

### PR DESCRIPTION
**Pull request by aurimus**
Closes PopcornTimeCommunity/desktop#79

It's dirty implementation, but it corresponds to the way it works currently.

### CODE REVIEW

**Comment by YIFYtorrents** [comment]
I tried your code and it doesn't work at all, but thank you for trying to help. 

I think the index and the last modified value are the same. I also tried renaming and playing  a torrent from the collection but the order is still the same. Your code is missing someting. Please tell what action is necessary in order to change the value of last modified.

oh and sorry for the late reply. I had some medical issues.

**Comment by aurimus** [comment]
Can you try the other PR? It's continuation of this one, but it is brought further (It might fix it for you, just don't forget `npm install`)

**Comment by YIFYtorrents** [comment]
What is PR? I have only edited torrent-collection.tpl and js. Sir, what else do I need to edit to make it work? 

I had medical issues the last 6 month. Actually I had breathing problems after to much popcorn time coding. I was not active at all, but this popcorn time repo will get new big updates now. I found the solution by doing some sport.

Thank you for helping.

**Comment by YIFYtorrents** [comment]
I also noticed  very much activity, commits, etc from you. That is appreciated. Keep up the good work.

**Comment by aurimus** [comment]
PR is a pull request :D .. do you know how git works? Make sure you go through https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control .. otherwise it would be hard to tell you.

I suggest you just click the green button Merge bellow because I tested it, it works at least on Ubuntu .. if it doesn't - somebody will report a bug.

**Comment by YIFYtorrents** [comment]
lol you made me laugh. of course I know how git work, been almost working a year on it. Anyways I will merge your PR as soon as I have reviewed your code. I hope I will find time to review it.

Again, thank you and keep up the good work

**Comment by aurimus** [comment]
Yea, well, you don't have to manually review it, just check it out locally and test how it runs ;)

**Comment by YIFYtorrents** [comment]
I am reviewing your PR now.

**Pull request merged**
