### PR TITLE
"Refix" app url

### PR DESCRIPTION
**Pull request by mauler**
My popcorn it's starting only if I change this value o package.json

### CODE REVIEW

**Comment by mauler** [comment]
Fixes
https://github.com/PopcornTimeCommunity/desktop/issues/104

**Comment by YIFYtorrents** [comment]
for me it's only showing popcorn time images in [about.tpl](https://github.com/PopcornTimeCommunity/desktop/blob/master/src/app/templates/about.tpl) if I change `main` value on package.json to 

`"main": "app://host/src/app/index.html",`

reference: https://github.com/PopcornTimeCommunity/desktop/commit/b93ab7de144af4a591b2ce0584636fb4d2be03d4

**Comment by AirLancer** [comment]
I can confirm @mauler 's behaviour.
I can only start popcorn time if I change `main` value on package.json to

`"main": "src/app/index.html",`

I'm using MacOS Sierra if that is of interest.

**Comment by mauler** [comment]
@YIFYtorrents  @AirLancer  up

**Comment by YIFYtorrents** [comment]
@mauler the issue is fixed now. thank you men

**Pull request merged**
